services:
  postgres-db:
    image: postgres:15  # You can specify the PostgreSQL version you want
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data  # To persist data
    ports:
      - "5432:5432"  # Exposing port 5432 to host

volumes:
  postgres-data:
